// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIwKia_pfik7ekVHvbMD9Xgdzv_NQ_9RA',
    appId: '1:1059641094292:web:43f215ba70d434089a4481',
    messagingSenderId: '1059641094292',
    projectId: 'swn-tracen-785a0',
    authDomain: 'swn-tracen-785a0.firebaseapp.com',
    storageBucket: 'swn-tracen-785a0.firebasestorage.app',
    measurementId: 'G-5QYW8DP8TF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN_ROuyy5zCV0HunRaWV_gf3doQ1qLUKA',
    appId: '1:1059641094292:android:a32bb1556ff782ad9a4481',
    messagingSenderId: '1059641094292',
    projectId: 'swn-tracen-785a0',
    storageBucket: 'swn-tracen-785a0.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD76Z52_IoC83FycNtpToaZIJUHnvEaqSw',
    appId: '1:1059641094292:ios:88ac5392f439b68c9a4481',
    messagingSenderId: '1059641094292',
    projectId: 'swn-tracen-785a0',
    storageBucket: 'swn-tracen-785a0.firebasestorage.app',
    androidClientId: '1059641094292-5vr6t1dg5uemgllb2gv174bhh10p59uk.apps.googleusercontent.com',
    iosClientId: '1059641094292-qnhs86192mhfabgvvlbg6m7ognejsm15.apps.googleusercontent.com',
    iosBundleId: 'com.khuslen.aa',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD76Z52_IoC83FycNtpToaZIJUHnvEaqSw',
    appId: '1:1059641094292:ios:88ac5392f439b68c9a4481',
    messagingSenderId: '1059641094292',
    projectId: 'swn-tracen-785a0',
    storageBucket: 'swn-tracen-785a0.firebasestorage.app',
    androidClientId: '1059641094292-5vr6t1dg5uemgllb2gv174bhh10p59uk.apps.googleusercontent.com',
    iosClientId: '1059641094292-qnhs86192mhfabgvvlbg6m7ognejsm15.apps.googleusercontent.com',
    iosBundleId: 'com.khuslen.aa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBb_GCmuis03tRfpf1DVBEpJ2XxgLjK9ww',
    appId: '1:1059641094292:web:a04dc41a2d08ade79a4481',
    messagingSenderId: '1059641094292',
    projectId: 'swn-tracen-785a0',
    authDomain: 'swn-tracen-785a0.firebaseapp.com',
    storageBucket: 'swn-tracen-785a0.firebasestorage.app',
    measurementId: 'G-GWG5V03MJ4',
  );
}
