// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIwKia_pfik7ekVHvbMD9Xgdzv_NQ_9RA',
    appId: '1:1059641094292:web:43f215ba70d434089a4481',
    messagingSenderId: '1059641094292',
    projectId: 'swn-tracen-785a0',
    authDomain: 'swn-tracen-785a0.firebaseapp.com',
    storageBucket: 'swn-tracen-785a0.firebasestorage.app',
    measurementId: 'G-5QYW8DP8TF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN_ROuyy5zCV0HunRaWV_gf3doQ1qLUKA',
    appId: '1:1059641094292:android:bc27d12a6dfc723e9a4481',
    messagingSenderId: '1059641094292',
    projectId: 'swn-tracen-785a0',
    storageBucket: 'swn-tracen-785a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbxOsHIXvc67XVgu7tw880CPHAyoeunlI',
    appId: '1:1059641094292:ios:9f8519e5b38571d49a4481',
    messagingSenderId: '1059641094292',
    projectId: 'swn-tracen-785a0',
    storageBucket: 'swn-tracen-785a0.firebasestorage.app',
    iosBundleId: 'com.khuslen.tracen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbxOsHIXvc67XVgu7tw880CPHAyoeunlI',
    appId: '1:1059641094292:ios:9f8519e5b38571d49a4481',
    messagingSenderId: '1059641094292',
    projectId: 'swn-tracen-785a0',
    storageBucket: 'swn-tracen-785a0.firebasestorage.app',
    iosBundleId: 'com.khuslen.tracen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIwKia_pfik7ekVHvbMD9Xgdzv_NQ_9RA',
    appId: '1:1059641094292:web:c2a589c3f0d04b469a4481',
    messagingSenderId: '1059641094292',
    projectId: 'swn-tracen-785a0',
    authDomain: 'swn-tracen-785a0.firebaseapp.com',
    storageBucket: 'swn-tracen-785a0.firebasestorage.app',
    measurementId: 'G-VFQ2Q7Z61D',
  );
}
